-- 방법 1. LEFT JOIN 사용
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
LEFT JOIN ITEM_TREE T
ON I.ITEM_ID = T.PARENT_ITEM_ID
WHERE T.ITEM_ID IS NULL
ORDER BY I.ITEM_ID DESC;

/* -- 방법 2. NOT IN 사용
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID NOT IN (              -- NOT IN 사용 시 >  WHERE 절에 IS NOT NULL 필수
    SELECT DISTINCT PARENT_ITEM_ID  -- 업그레이드 가능
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL
)
ORDER BY ITEM_ID DESC;
*/