SELECT DISTINCT A.CAR_ID, A.CAR_TYPE,
    ROUND(A.DAILY_FEE * (100 - B.DISCOUNT_RATE) / 100 * 30, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
ON A.CAR_TYPE = B.CAR_TYPE
WHERE A.CAR_TYPE IN ('세단', 'SUV')
     AND A.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
     )
     AND B.DURATION_TYPE = '30일 이상'
     AND ROUND(A.DAILY_FEE * (100 - B.DISCOUNT_RATE) / 100 * 30, 0) >= 500000
     AND ROUND(A.DAILY_FEE * (100 - B.DISCOUNT_RATE) / 100 * 30, 0) < 2000000
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC;