SELECT ROUTE, 
    CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1), 'km') AS TOTAL_DISTANCE,
    CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY ROUND(SUM(D_BETWEEN_DIST), 1) DESC

# TOTAL_DISTANCE는 CONCAT을 사용하여 String으로 처리됨.
# 따라서, 정렬할 때 TOTAL_DISTANCE가 아닌 ROUND(SUM(D_BETWEEN_DIST), 1)를 사용해야 함.