WITH RECURSIVE TREE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, T.GENERATION + 1
    FROM TREE T      -- 부모
    JOIN ECOLI_DATA E        -- 자식
    ON T.ID = E.PARENT_ID
)

SELECT COUNT(*) AS COUNT, T.GENERATION
FROM TREE T
LEFT JOIN ECOLI_DATA E
ON T.ID = E.PARENT_ID
WHERE E.ID IS NULL
GROUP BY GENERATION
ORDER BY GENERATION;