WITH RECURSIVE TIME AS (
    SELECT 0 AS H
    UNION ALL
    SELECT H + 1 FROM TIME WHERE H < 23
)

SELECT T.H AS HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM TIME T
LEFT JOIN ANIMAL_OUTS A
ON T.H = HOUR(A.DATETIME)
GROUP BY HOUR
ORDER BY HOUR;