SELECT B.EMP_NO, B.EMP_NAME,
    CASE
        WHEN AVG(C.SCORE)>= 96 THEN 'S'
        WHEN AVG(C.SCORE) >= 90 THEN 'A'
        WHEN AVG(C.SCORE) >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE
        WHEN AVG(C.SCORE) >= 96 THEN ROUND(B.SAL * 20 / 100, 0)
        WHEN AVG(C.SCORE) >= 90 THEN ROUND(B.SAL * 15 / 100, 0)
        WHEN AVG(C.SCORE) >= 80 THEN ROUND(B.SAL * 10 / 100, 0)
        ELSE 0
    END AS BONUS
FROM HR_DEPARTMENT A
JOIN HR_EMPLOYEES B
ON A.DEPT_ID = B.DEPT_ID
JOIN HR_GRADE C
ON B.EMP_NO = C.EMP_NO
GROUP BY B.EMP_NO
ORDER BY B.EMP_NO;