SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
JOIN SKILLCODES S
ON D.SKILL_CODE & S.CODE > 0
WHERE S.NAME IN ('PYTHON', 'C#')   # WHERE S.NAME ='PYTHON' OR S.NAME = 'C#'
ORDER BY D.ID

# SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
# FROM DEVELOPERS
# WHERE SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'PYTHON')
# OR SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')
# ORDER BY ID