SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO A
JOIN FISH_NAME_INFO B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE (A.FISH_TYPE, A.LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
ORDER BY A.ID;

/* 윈도우함수 + 서브쿼리 (Ranking)
SELECT ID, FISH_NAME, LENGTH
FROM (
    SELECT A.ID, B.FISH_NAME, A.LENGTH,
        RANK() OVER (PARTITION BY A.FISH_TYPE ORDER BY A.LENGTH DESC) AS RK
    FROM FISH_INFO A 
    JOIN FISH_NAME_INFO B
    ON A.FISH_TYPE = B.FISH_TYPE
) T
WHERE RK = 1
ORDER BY ID;
*/